"""
Django settings for osrm project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os
import ConfigParser

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ISOTIMEFORMAT='%Y-%m-%dT%X'
config = ConfigParser.ConfigParser()
config.read(os.path.join(BASE_DIR, 'syscfg.conf'))
# ======== Log ==========
LOG_DIR = os.path.join(BASE_DIR, 'logs')
LOG_LEVEL = config.get('base', 'log')
config = ConfigParser.ConfigParser()
config.read(os.path.join(BASE_DIR, 'syscfg.conf'))

# get redis config 

REDIS_HOST      = config.get('redis','host')
REDIS_PORT      = config.get('redis','PORT')
REDIS_PASSWD    = config.get('redis','passwd')

# get mq config

MQ_IP         = config.get('mq','mqip')
MQ_PORT       = config.get('mq','mqport')
MQ_CCSID      = config.get('mq','mqccsid')
MQ_MANAGER    = config.get('mq','mqmanager')
MQ_LABEL      = config.get('mq','mqlabel')
MQ_CHANNEL    = config.get('mq','mqchannel')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'nt58!r9=7wls8j09s09tdsju9d!r%8^dj8b(d90g8944v5ajv5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'osrm',
    'cm'
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
    #'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',

ROOT_URLCONF = 'osrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'osrm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases


DATABASES = {}
if config.get('db', 'engine') == 'mysql': 
    DB_HOST = config.get('db', 'host')
    DB_PORT = config.get('db', 'port')
    DB_USER = config.get('db', 'user')
    DB_PASSWORD = config.get('db', 'password')
    DB_DATABASE = config.get('db', 'database')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': DB_DATABASE,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        }
    }
elif config.get('db','engine') == 'oracle':
    DB_HOST = config.get('db', 'host')
    DB_PORT = config.get('db', 'port')
    DB_USER = config.get('db', 'user')
    DB_PASSWORD = config.get('db', 'password')
    DB_DATABASE = config.get('db', 'database')
    DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': DB_DATABASE,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
}
elif config.get('db', 'engine') == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': config.get('db', 'database'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

LOGGING = {  
    'version': 1,  
    'disable_existing_loggers': False,  
    'formatters': {  
        'standard': {  
  
            'format': '%(asctime)s [%(threadName)s:%(thread)d] [%(name)s:%(lineno)d] [%(levelname)s]- %(message)s'  
        },  
    },  
    'filters': {  
    },  
    'handlers': {  
        'default': {  
            'level':'DEBUG',  
            'class':'logging.handlers.RotatingFileHandler',  
            'filename': os.path.join(LOG_DIR,'server.log'),  
            'maxBytes': 1024*1024*100,  
            'backupCount': 5,  
            'formatter':'standard',  
        },  
        'request_handler': {  
            'level':'DEBUG',  
            'class':'logging.handlers.RotatingFileHandler',  
            'filename': os.path.join(LOG_DIR,'request.log'),
            'maxBytes': 1024*1024*100,  
            'backupCount': 5,  
            'formatter':'standard',  
        },  
        'console':{
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'standard'
        },
    },  
    'loggers': {  
        'django': {  
            'handlers': ['default','console'],  
            'level': LOG_LEVEL,  
            'propagate': True   
        },  
        'django.request': {  
            'handlers': ['request_handler','console'],  
            'level': LOG_LEVEL,  
            'propagate': True   
        },  
    }  
}  
# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
